location = /vue-sentry-starter {
    return 301 /vue-sentry-starter/;
}

location ^~ /vue-sentry-starter/ {
    alias /var/www/vue-sentry-starter/current/;
    try_files $uri $uri/ /vue-sentry-starter/index.html;
}
